import { Request, Response, NextFunction } from 'express';
import { JWTClaims, UserRole } from '../types/index.js';

const permissions: Record<UserRole, Record<string, string[]>> = {
	super_admin: {
		properties: ['*'],
		units: ['*'],
		tenants: ['*'],
		caretakers: ['*'],
		staff: ['*'],
		agents: ['*'],
		dashboard: ['*'],
		financial: ['*'],
		invoices: ['*'],
		maintenance: ['*'],
		inspections: ['*'],
		communications: ['*'],
		notifications: ['*'],
		messages: ['*'],
		reports: ['*'],
		assignments: ['*'],
		leases: ['*'],
		payments: ['*'],
		billing: ['*'],
		tasks: ['*'],
		movements: ['*'],
		conditions: ['*'],
		users: ['*'],
		companies: ['*'],
		checklists: ['*'],
		emergency: ['*'],
	},
	agency_admin: {
		properties: ['create', 'read', 'update', 'delete', 'archive', 'duplicate', 'settings', 'history'],
		units: ['create', 'read', 'update', 'delete', 'assign', 'release', 'photos', 'status'],
		tenants: ['create', 'read', 'update', 'delete'],
		caretakers: ['create', 'read', 'update', 'delete', 'invite'],
		staff: ['create', 'read', 'update', 'delete', 'invite'],
		agents: ['create', 'read', 'update', 'delete', 'assign'],
		dashboard: ['read', 'kpis', 'charts'],
		financial: ['read', 'overview', 'payments', 'rent-collection'],
		invoices: ['create', 'read', 'update', 'delete', 'send', 'mark-paid', 'export', 'bulk', 'stats'],
		maintenance: ['create', 'read', 'update', 'delete', 'overview'],
		inspections: ['create', 'read', 'update', 'delete', 'overview', 'schedule'],
		communications: ['create', 'read', 'update', 'templates', 'overview'],
		notifications: ['create', 'read', 'update', 'delete', 'bulk'],
		messages: ['create', 'read', 'update', 'delete'],
		reports: ['read', 'generate'],
		assignments: ['read', 'create', 'update'],
		leases: ['create', 'read', 'update'],
		payments: ['create', 'read', 'update', 'approve', 'delete'],
		agreements: ['create', 'read', 'update'],
		tasks: ['create', 'read', 'update'],
		movements: ['read', 'update'],
		conditions: ['create', 'read', 'update'],
		billing: ['create', 'read', 'update', 'stats'],
		settings: ['read', 'update'],
		users: ['create', 'read', 'update', 'delete'],
		checklists: ['create', 'read', 'update', 'delete'],
		emergency: ['create', 'read', 'update', 'delete'],
	},
	landlord: {
		properties: ['create', 'read', 'update', 'delete', 'archive', 'duplicate', 'settings', 'history'],
		units: ['create', 'read', 'update', 'delete', 'assign', 'release', 'photos', 'status'],
		tenants: ['create', 'read', 'update', 'delete'],
		caretakers: ['create', 'read', 'update', 'delete', 'invite'],
		staff: ['create', 'read', 'update', 'delete', 'invite'],
		agents: ['create', 'read', 'update', 'delete', 'assign'],
		dashboard: ['read', 'update', 'kpis', 'charts'],
		financial: ['read', 'overview', 'payments', 'rent-collection'],
		invoices: ['create', 'read', 'update', 'delete', 'send', 'mark-paid', 'export', 'bulk', 'stats'],
		maintenance: ['create', 'read', 'update', 'delete', 'overview'],
		inspections: ['create', 'read', 'update', 'delete', 'overview', 'schedule'],
		communications: ['create', 'read', 'update', 'templates', 'overview'],
		notifications: ['create', 'read', 'update', 'delete', 'bulk'],
		messages: ['create', 'read', 'update', 'delete'],
		reports: ['read', 'generate'],
		assignments: ['read', 'create', 'update'],
		leases: ['create', 'read', 'update'],
		payments: ['create', 'read', 'update', 'approve', 'delete'],
		agreements: ['create', 'read', 'update'],
		tasks: ['create', 'read', 'update'],
		movements: ['read', 'update'],
		conditions: ['create', 'read', 'update'],
		billing: ['create', 'read', 'update', 'stats'],
		settings: ['read', 'update'],
		users: ['create', 'read', 'update', 'delete'],
		checklists: ['create', 'read', 'update', 'delete'],
		emergency: ['create', 'read', 'update', 'delete'],
	},
	agent: {
		properties: ['read'],
		units: ['read', 'update', 'assign', 'release'],
		tenants: ['create', 'read', 'update'],
		staff: ['create', 'read', 'update', 'delete', 'invite'],
		dashboard: ['read'],
		invoices: ['create', 'read', 'update', 'send', 'mark-paid', 'export', 'bulk', 'stats'],
		maintenance: ['create', 'read'],
		communications: ['create', 'read'],
		notifications: ['create', 'read', 'update'],
		messages: ['create', 'read', 'update'],
		payments: ['create', 'read', 'approve'],
		leases: ['create', 'read'],
		assignments: ['read'],
		checklists: ['create', 'read', 'update'],
		emergency: ['read'],
	},
	caretaker: {
		properties: ['read'],
		units: ['read', 'update', 'photos'],
		tenants: ['read'],
		dashboard: ['read'],
		maintenance: ['create', 'read', 'update', 'overview'],
		tasks: ['read', 'update', 'create'],
		conditions: ['create', 'read', 'update'],
		movements: ['read', 'update'],
		inspections: ['create', 'read', 'update'],
		communications: ['create', 'read'],
		notifications: ['create', 'read', 'update'],
		messages: ['create', 'read', 'update'],
		reports: ['read'],
		leases: ['read'],
		payments: ['create', 'read'],
		assignments: ['read'],
		checklists: ['create', 'read', 'update'],
		emergency: ['read'],
	},
	tenant: {
		units: ['read'],
		maintenance: ['create', 'read'],
		invoices: ['read'],
		payments: ['read', 'create'], // Allow tenants to read and create (cancel) their own payments
		notifications: ['create', 'read', 'update', 'delete'], // Allow tenants to delete their own notifications
		messages: ['create', 'read', 'update', 'delete'], // Allow tenants to manage their own messages
		communications: ['create', 'read'],
		checklists: ['read', 'update'],
	},
	cleaner: {
		properties: ['read'],
		units: ['read'],
		tenants: ['read'],
		dashboard: ['read'],
		maintenance: ['read', 'update'],
		communications: ['read'],
		notifications: ['read'],
		messages: ['read'],
		tasks: ['read', 'update'],
		checklists: ['read'],
	},
	security: {
		properties: ['read'],
		units: ['read'],
		tenants: ['read'],
		dashboard: ['read'],
		maintenance: ['read', 'update'],
		communications: ['read'],
		notifications: ['read'],
		messages: ['read'],
		tasks: ['read', 'update'],
		checklists: ['read'],
	},
	maintenance: {
		properties: ['read'],
		units: ['read', 'update', 'photos'],
		tenants: ['read'],
		dashboard: ['read'],
		maintenance: ['create', 'read', 'update', 'overview'],
		tasks: ['read', 'update', 'create'],
		conditions: ['create', 'read', 'update'],
		movements: ['read', 'update'],
		inspections: ['create', 'read', 'update'],
		communications: ['create', 'read'],
		notifications: ['create', 'read', 'update'],
		messages: ['create', 'read', 'update'],
		reports: ['read'],
		leases: ['read'],
		payments: ['create', 'read'],
		assignments: ['read'],
		checklists: ['create', 'read', 'update'],
		emergency: ['read'],
	},
	receptionist: {
		properties: ['read'],
		units: ['read'],
		tenants: ['read'],
		dashboard: ['read'],
		communications: ['read'],
		notifications: ['read'],
		messages: ['read'],
		tasks: ['read', 'update'],
	},
	accountant: {
		properties: ['read'], // Read-only, no creation
		units: ['read'],
		tenants: ['read'], // Read-only, no editing
		dashboard: ['read'],
		financial: ['read', 'overview', 'payments', 'rent-collection'],
		invoices: ['read', 'update', 'export', 'stats'],
		payments: ['read', 'update', 'approve'],
		reports: ['read', 'generate'],
		leases: ['read'],
	},
	admin: {
		properties: ['read', 'update'],
		units: ['read', 'update'],
		tenants: ['read', 'update'],
		dashboard: ['read', 'kpis', 'charts'],
		financial: ['read', 'overview'],
		invoices: ['read', 'update'],
		maintenance: ['read', 'update'],
		inspections: ['read', 'update'],
		communications: ['create', 'read', 'update'],
		notifications: ['create', 'read', 'update'],
		messages: ['create', 'read', 'update'],
		reports: ['read', 'generate'],
		leases: ['read', 'update'],
		payments: ['read', 'update'],
		tasks: ['create', 'read', 'update'],
		users: ['read', 'update'],
		checklists: ['read', 'update'],
	},
	manager: {
		properties: ['read', 'update'],
		units: ['read', 'update'],
		tenants: ['read', 'update'],
		dashboard: ['read', 'kpis', 'charts'],
		financial: ['read', 'overview'],
		invoices: ['read', 'update'],
		maintenance: ['read', 'update', 'overview'],
		inspections: ['read', 'update', 'schedule'],
		communications: ['create', 'read', 'update'],
		notifications: ['create', 'read', 'update'],
		messages: ['create', 'read', 'update'],
		reports: ['read', 'generate'],
		leases: ['read', 'update'],
		payments: ['read', 'update'],
		tasks: ['create', 'read', 'update'],
		users: ['read', 'update'],
		checklists: ['read', 'update'],
	},
	team_lead: {
		properties: ['read'],
		units: ['read'],
		tenants: ['read', 'update'],
		dashboard: ['read'],
		invoices: ['read'],
		maintenance: ['read', 'update'],
		inspections: ['read', 'update'],
		communications: ['create', 'read', 'update'],
		notifications: ['create', 'read', 'update'],
		messages: ['create', 'read', 'update'],
		reports: ['read'],
		leases: ['read'],
		payments: ['read'],
		tasks: ['create', 'read', 'update'],
		checklists: ['read', 'update'],
	},
	staff: {
		properties: ['read'],
		units: ['read'],
		tenants: ['read'],
		dashboard: ['read'],
		maintenance: ['read', 'update'],
		communications: ['read'],
		notifications: ['read'],
		messages: ['read'],
		tasks: ['read', 'update'],
		checklists: ['read'],
	},
	finance: {
		properties: ['read'], // Read-only, no creation
		units: ['read'],
		tenants: ['read'], // Read-only, no editing
		dashboard: ['read'],
		financial: ['read', 'overview', 'payments', 'rent-collection'],
		invoices: ['read', 'update', 'export', 'stats'],
		payments: ['read', 'update', 'approve'],
		reports: ['read', 'generate'],
		leases: ['read'],
	},
	sales: {
		tenants: ['create', 'read', 'update'], // Can manage tenants
		dashboard: ['read'],
		communications: ['create', 'read', 'update'], // Follow-ups
		notifications: ['create', 'read', 'update'],
		messages: ['create', 'read', 'update'],
		leases: ['read'],
		tasks: ['create', 'read', 'update'], // Follow-up tasks
		// No system settings, no finance data
	},
	marketing: {
		properties: ['read'],
		units: ['read'],
		tenants: ['read'],
		dashboard: ['read', 'charts'],
		communications: ['create', 'read', 'update', 'templates'],
		notifications: ['create', 'read', 'update', 'bulk'],
		messages: ['create', 'read', 'update'],
		reports: ['read', 'generate'],
	},
	support: {
		properties: ['read'],
		units: ['read'],
		tenants: ['read', 'update'],
		dashboard: ['read'],
		maintenance: ['read', 'update'],
		communications: ['create', 'read', 'update'],
		notifications: ['create', 'read', 'update'],
		messages: ['create', 'read', 'update'],
		tasks: ['read', 'update'],
		checklists: ['read'],
	},
	hr: {
		users: ['create', 'read', 'update', 'delete'],
		staff: ['create', 'read', 'update', 'delete', 'invite'],
		dashboard: ['read'],
		reports: ['read', 'generate'],
		communications: ['read'],
		notifications: ['read'],
		messages: ['read'],
	},
	auditor: {
		properties: ['read'],
		units: ['read'],
		tenants: ['read'],
		dashboard: ['read'],
		financial: ['read'],
		invoices: ['read'],
		payments: ['read'],
		reports: ['read', 'generate'],
		leases: ['read'],
		users: ['read'],
		// Read-only access to everything for auditing
	},
};

export const rbacResource = (resource: string, action: string) => (req: Request, res: Response, next: NextFunction) => {
	const user = (req as any).user as JWTClaims | undefined;
	if (!user) {
		return res.status(401).json({ success: false, message: 'Unauthorized' });
	}
	const allowed = permissions[user.role]?.[resource];
	if (!allowed) {
		return res.status(403).json({ success: false, message: `Role '${user.role}' does not have permission to '${action}' on '${resource}'` });
	}
	if (!(allowed.includes('*') || allowed.includes(action))) {
		return res.status(403).json({ success: false, message: `Role '${user.role}' does not have permission to '${action}' on '${resource}'` });
	}
	return next();
};

export const buildPermissionMatrix = () => permissions;
